export interface Product {
  id: number;
  name: string;
  categoria: string;
  linea: string;
  aroma: string;
  formato: string;
  precio: number;
  badge: string | null;
  biodegradable: boolean;
  concentrado: boolean;
  img: string;
  desc: string;
}

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Sapolio Limpiapisos Lavanda",
    categoria: "Pisos",
    linea: "Sapolio",
    aroma: "Lavanda",
    formato: "900ml",
    precio: 12.5,
    badge: "Más vendido",
    biodegradable: true,
    concentrado: false,
    img: "https://images.unsplash.com/photo-1585421514738-01798e348b17?q=80&w=600",
    desc: "Limpiapisos Sapolio con fragancia a lavanda. Limpia profundo y deja un aroma duradero en todo tipo de pisos.",
  },
  {
    id: 2,
    name: "Sapolio Desinfectante Pino",
    categoria: "Desinfectante",
    linea: "Sapolio",
    aroma: "Pino",
    formato: "500ml",
    precio: 9.9,
    badge: null,
    biodegradable: true,
    concentrado: false,
    img: "https://images.unsplash.com/photo-1563453392212-326f5e854473?q=80&w=600",
    desc: "Desinfectante multiusos Sapolio con aroma a pino. Elimina el 99.9% de gérmenes y bacterias del hogar.",
  },
  {
    id: 3,
    name: "Clorox Lejía Tradicional",
    categoria: "Desinfectante",
    linea: "Clorox",
    aroma: "Neutro",
    formato: "1L",
    precio: 8.5,
    badge: null,
    biodegradable: false,
    concentrado: true,
    img: "https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?q=80&w=600",
    desc: "Lejía Clorox de uso doméstico e industrial. Desinfecta, blanquea y elimina olores con fórmula concentrada.",
  },
  {
    id: 4,
    name: "Clorox Desinfectante Floral",
    categoria: "Multiusos",
    linea: "Clorox",
    aroma: "Floral",
    formato: "900ml",
    precio: 14.0,
    badge: "Nuevo",
    biodegradable: false,
    concentrado: false,
    img: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=600",
    desc: "Desinfectante líquido Clorox con fragancia floral. Ideal para pisos, baños y superficies de cocina.",
  },
  {
    id: 5,
    name: "Hude Lavavajillas Limón",
    categoria: "Cocina",
    linea: "Hude",
    aroma: "Limón",
    formato: "500ml",
    precio: 7.5,
    badge: null,
    biodegradable: true,
    concentrado: false,
    img: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?q=80&w=600",
    desc: "Lavavajillas Hude con extracto de limón. Corta la grasa al instante y cuida tus manos con su fórmula suave.",
  },
  {
    id: 6,
    name: "Hude Desengrasante Industrial",
    categoria: "Desengrasante",
    linea: "Hude",
    aroma: "Neutro",
    formato: "1L",
    precio: 18.0,
    badge: "Premium",
    biodegradable: false,
    concentrado: true,
    img: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=600",
    desc: "Desengrasante concentrado Hude para uso industrial y comercial. Remueve grasa y aceite en cocinas de alto tráfico.",
  },
  {
    id: 7,
    name: "Baygon Mata Insectos Voladores",
    categoria: "Insecticida",
    linea: "Baygon",
    aroma: "Neutro",
    formato: "360ml",
    precio: 22.0,
    badge: null,
    biodegradable: false,
    concentrado: false,
    img: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=600",
    desc: "Insecticida Baygon en aerosol para mosquitos, moscas y zancudos. Acción rápida y efectiva.",
  },
  {
    id: 8,
    name: "Baygon Mata Rastreros",
    categoria: "Insecticida",
    linea: "Baygon",
    aroma: "Neutro",
    formato: "360ml",
    precio: 22.0,
    badge: null,
    biodegradable: false,
    concentrado: false,
    img: "https://images.unsplash.com/photo-1585421514738-01798e348b17?q=80&w=600",
    desc: "Insecticida Baygon para cucarachas, hormigas y arañas. Protección hasta 4 semanas en superficies tratadas.",
  },
  {
    id: 9,
    name: "Glade Toque Lavanda & Vainilla",
    categoria: "Aromas",
    linea: "Glade",
    aroma: "Lavanda",
    formato: "270ml",
    precio: 19.9,
    badge: "Exclusivo",
    biodegradable: true,
    concentrado: false,
    img: "https://images.unsplash.com/photo-1604335399105-a0c585fd81a1?q=80&w=600",
    desc: "Ambientador Glade Toque con fragancia Lavanda & Vainilla. Elimina malos olores al instante con cada toque.",
  },
  {
    id: 10,
    name: "Glade Eléctrico Bosque",
    categoria: "Aromas",
    linea: "Glade",
    aroma: "Bosque",
    formato: "Kit",
    precio: 34.9,
    badge: null,
    biodegradable: true,
    concentrado: false,
    img: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=600",
    desc: "Kit aromatizador eléctrico Glade con fragancia Bosque. Difunde aroma continuo por hasta 30 días.",
  },
  {
    id: 11,
    name: "Elite Papel Higiénico Triple Hoja",
    categoria: "Papel",
    linea: "Elite",
    aroma: "Neutro",
    formato: "Pack x4",
    precio: 11.0,
    badge: null,
    biodegradable: true,
    concentrado: false,
    img: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=600",
    desc: "Papel higiénico Elite triple hoja. Máxima suavidad y resistencia para el cuidado de toda la familia.",
  },
  {
    id: 12,
    name: "Elite Papel Toalla Jumbo",
    categoria: "Papel",
    linea: "Elite",
    aroma: "Neutro",
    formato: "2 rollos",
    precio: 9.5,
    badge: null,
    biodegradable: true,
    concentrado: false,
    img: "https://images.unsplash.com/photo-1556911073-52527ac43761?q=80&w=600",
    desc: "Papel toalla Elite doble hoja jumbo. Alta absorción para cocina, baño y uso comercial.",
  },
  {
    id: 13,
    name: "Suavitel Toque de Suavidad",
    categoria: "Textil",
    linea: "Suavitel",
    aroma: "Floral",
    formato: "850ml",
    precio: 13.5,
    badge: null,
    biodegradable: true,
    concentrado: false,
    img: "https://images.unsplash.com/photo-1604335399105-a0c585fd81a1?q=80&w=600",
    desc: "Suavizante Suavitel con fragancia floral duradera. Deja la ropa suave, esponjosa y con aroma fresco por días.",
  },
  {
    id: 14,
    name: "Suavitel Concentrado Bebé",
    categoria: "Textil",
    linea: "Suavitel",
    aroma: "Talco",
    formato: "500ml",
    precio: 15.0,
    badge: "Nuevo",
    biodegradable: true,
    concentrado: true,
    img: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?q=80&w=600",
    desc: "Suavizante concentrado Suavitel fórmula bebé. Hipoalergénico, con fragancia suave a talco para ropa delicada.",
  },
  {
    id: 15,
    name: "Daryza Detergente en Polvo",
    categoria: "Textil",
    linea: "Daryza",
    aroma: "Floral",
    formato: "1kg",
    precio: 10.5,
    badge: null,
    biodegradable: true,
    concentrado: false,
    img: "https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?q=80&w=600",
    desc: "Detergente en polvo Daryza con fórmula antimancha. Limpieza profunda en lavado a mano o a máquina.",
  },
  {
    id: 16,
    name: "Martell Limpiador Pisos Menta",
    categoria: "Pisos",
    linea: "Martell",
    aroma: "Menta",
    formato: "1L",
    precio: 11.0,
    badge: null,
    biodegradable: true,
    concentrado: false,
    img: "https://images.unsplash.com/photo-1585421514738-01798e348b17?q=80&w=600",
    desc: "Limpiapisos Martell con aroma a menta. Ideal para pisos cerámicos, cemento y vinílicos. Rinde hasta 40 litros.",
  },
  {
    id: 17,
    name: "Dayr Desengrasante Cocina",
    categoria: "Desengrasante",
    linea: "Dayr",
    aroma: "Cítrico",
    formato: "500ml",
    precio: 12.0,
    badge: null,
    biodegradable: true,
    concentrado: false,
    img: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=600",
    desc: "Desengrasante Dayr con activos cítricos. Disuelve grasa acumulada en cocinas industriales y domésticas.",
  },
  {
    id: 18,
    name: "Kit Limpieza Hogar Completo",
    categoria: "Kits",
    linea: "Sapolio",
    aroma: "Mixto",
    formato: "Kit x5",
    precio: 55.0,
    badge: "Oferta",
    biodegradable: true,
    concentrado: false,
    img: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=600",
    desc: "Kit completo de limpieza: limpiapisos, desinfectante, lavavajillas, desengrasante y ambientador Sapolio.",
  },
];

export const CATEGORIAS = [
  "Todas",
  "Pisos",
  "Desinfectante",
  "Multiusos",
  "Cocina",
  "Desengrasante",
  "Insecticida",
  "Aromas",
  "Papel",
  "Textil",
  "Kits",
];

export const LINEAS = [
  "Sapolio",
  "Clorox",
  "Hude",
  "Baygon",
  "Glade",
  "Elite",
  "Suavitel",
  "Daryza",
  "Martell",
  "Dayr",
];

export const AROMAS = [
  "Lavanda",
  "Pino",
  "Neutro",
  "Floral",
  "Limón",
  "Cítrico",
  "Menta",
  "Talco",
  "Bosque",
  "Mixto",
];

export const FORMATOS = [
  "270ml",
  "360ml",
  "500ml",
  "850ml",
  "900ml",
  "1L",
  "1kg",
  "2 rollos",
  "Pack x4",
  "Kit",
  "Kit x5",
];

export const BADGE_STYLES: Record<string, string> = {
  "Más vendido": "bg-terracota text-white",
  Nuevo: "bg-musgo text-white",
  Premium: "bg-stone-900 text-white",
  Exclusivo: "bg-salvia text-stone-900",
  Oferta: "bg-amber-400 text-stone-900",
};
